# Generated by Django 5.2.7 on 2025-11-05 04:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human-readable name for this API key', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
                ('rate_limit_per_minute', models.IntegerField(default=60, help_text='Maximum requests per minute', validators=[django.core.validators.MinValueValidator(1)])),
                ('rate_limit_per_hour', models.IntegerField(default=1000, help_text='Maximum requests per hour', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_requests', models.BigIntegerField(default=0, help_text='Total number of requests made with this key')),
                ('total_tokens_processed', models.BigIntegerField(default=0, help_text='Total tokens processed')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the model')),
                ('model_path', models.CharField(help_text="Path or identifier for the model (e.g., 'meta-llama/Llama-2-7b-chat-hf')", max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_context_length', models.IntegerField(default=4096, help_text='Maximum context length in tokens', validators=[django.core.validators.MinValueValidator(1)])),
                ('default_temperature', models.FloatField(default=0.7, help_text='Default temperature for generation')),
                ('default_max_tokens', models.IntegerField(default=512, help_text='Default maximum tokens to generate', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_requests', models.BigIntegerField(default=0, help_text='Total requests processed')),
                ('total_responses', models.BigIntegerField(default=0, help_text='Total successful responses')),
                ('total_errors', models.BigIntegerField(default=0, help_text='Total errors encountered')),
                ('total_tokens_processed', models.BigIntegerField(default=0, help_text='Total tokens processed (input + output)')),
                ('total_input_tokens', models.BigIntegerField(default=0, help_text='Total input tokens')),
                ('total_output_tokens', models.BigIntegerField(default=0, help_text='Total output tokens')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='Input prompt text')),
                ('system_prompt', models.TextField(blank=True, help_text='Optional system prompt')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs or base64 encoded images')),
                ('temperature', models.FloatField(blank=True, help_text='Temperature for generation', null=True)),
                ('max_tokens', models.IntegerField(blank=True, help_text='Maximum tokens to generate', null=True)),
                ('top_p', models.FloatField(blank=True, help_text='Top-p sampling parameter', null=True)),
                ('top_k', models.IntegerField(blank=True, help_text='Top-k sampling parameter', null=True)),
                ('stream', models.BooleanField(default=False, help_text='Whether to stream the response')),
                ('response', models.TextField(blank=True, help_text='Generated response text')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed')),
                ('input_tokens', models.IntegerField(default=0, help_text='Number of input tokens')),
                ('output_tokens', models.IntegerField(default=0, help_text='Number of output tokens')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens (input + output)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('request_metadata', models.JSONField(blank=True, default=dict, help_text='Additional request metadata')),
                ('response_metadata', models.JSONField(blank=True, default=dict, help_text='Additional response metadata')),
                ('api_key', models.ForeignKey(help_text='API key used for this request', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='LLM.apikey')),
                ('model', models.ForeignKey(help_text='Model used for this request', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='LLM.model')),
            ],
            options={
                'verbose_name': 'LLM Request',
                'verbose_name_plural': 'LLM Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_key', '-created_at'], name='LLM_llmrequ_api_key_05e651_idx'), models.Index(fields=['model', '-created_at'], name='LLM_llmrequ_model_i_1591e1_idx'), models.Index(fields=['status', '-created_at'], name='LLM_llmrequ_status_aa54a7_idx')],
            },
        ),
    ]
