# Generated by Django 5.2.7 on 2025-11-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='huggingface_token',
            field=models.CharField(blank=True, help_text='HuggingFace token for accessing gated models (or set HF_TOKEN env var)', max_length=255),
        ),
    ]
