# Generated by Django 5.2.7 on 2025-11-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0002_model_huggingface_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='ollama_base_url',
            field=models.CharField(blank=True, default='http://localhost:11434', help_text='Ollama API base URL (default: http://localhost:11434)', max_length=255),
        ),
        migrations.AddField(
            model_name='model',
            name='provider',
            field=models.CharField(choices=[('vllm', 'vLLM'), ('ollama', 'Ollama')], default='vllm', help_text='Provider to use for this model', max_length=10),
        ),
    ]
