# Generated by Django 5.2.7 on 2025-11-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0003_model_ollama_base_url_model_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='alwayswarm',
            field=models.BooleanField(default=False, help_text='Keep this model warm by sending periodic requests'),
        ),
    ]
