# Generated by Django 5.2.7 on 2025-11-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0004_model_alwayswarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('embedding', 'Embedding')], default='chat', help_text='Type of model: chat for text generation, embedding for embeddings', max_length=10),
        ),
    ]
