# Generated by Django 5.2.7 on 2026-03-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0005_model_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmrequest',
            name='min_p',
            field=models.FloatField(blank=True, help_text='Min-p sampling parameter', null=True),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='presence_penalty',
            field=models.FloatField(blank=True, help_text='Presence penalty', null=True),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='repetition_penalty',
            field=models.FloatField(blank=True, help_text='Repetition penalty', null=True),
        ),
    ]
