# Generated by Django 5.2.7 on 2026-03-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0006_llmrequest_min_p_llmrequest_presence_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='default_min_p',
            field=models.FloatField(blank=True, help_text='Default min-p sampling parameter (leave blank to use provider default)', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='default_presence_penalty',
            field=models.FloatField(blank=True, help_text='Default presence penalty (leave blank to use provider default)', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='default_repetition_penalty',
            field=models.FloatField(blank=True, help_text='Default repetition penalty (leave blank to use provider default)', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='default_top_k',
            field=models.IntegerField(blank=True, help_text='Default top-k sampling parameter (leave blank to use provider default)', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='default_top_p',
            field=models.FloatField(blank=True, help_text='Default top-p sampling parameter (leave blank to use provider default)', null=True),
        ),
    ]
