# Generated by Django 5.2.7 on 2026-03-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0007_model_default_min_p_model_default_presence_penalty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='default_min_p',
            field=models.FloatField(default=0.0, help_text='Default min-p sampling parameter'),
        ),
        migrations.AlterField(
            model_name='model',
            name='default_presence_penalty',
            field=models.FloatField(default=1.5, help_text='Default presence penalty'),
        ),
        migrations.AlterField(
            model_name='model',
            name='default_repetition_penalty',
            field=models.FloatField(default=1.0, help_text='Default repetition penalty'),
        ),
        migrations.AlterField(
            model_name='model',
            name='default_top_k',
            field=models.IntegerField(default=20, help_text='Default top-k sampling parameter'),
        ),
        migrations.AlterField(
            model_name='model',
            name='default_top_p',
            field=models.FloatField(default=0.95, help_text='Default top-p sampling parameter'),
        ),
    ]
