# Generated by Django 5.2.7 on 2026-03-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0008_alter_model_default_min_p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmrequest',
            name='thinking',
            field=models.BooleanField(blank=True, help_text='Override model thinking mode for this request (null = use model default)', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='thinking_mode',
            field=models.CharField(choices=[('auto', 'Auto (let model decide)'), ('enabled', 'Enabled'), ('disabled', 'Disabled')], default='auto', help_text="Controls the model's internal reasoning/thinking mode (Ollama only)", max_length=10),
        ),
    ]
